/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddProspectDialog: typeof import('./src/components/crm/AddProspectDialog.vue')['default']
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    CustomerQuotesDialog: typeof import('./src/components/crm/CustomerQuotesDialog.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    InvoiceDetailDialog: typeof import('./src/components/crm/InvoiceDetailDialog.vue')['default']
    PageHeader: typeof import('./src/components/shared/PageHeader.vue')['default']
    QuoteDetailDialog: typeof import('./src/components/crm/QuoteDetailDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SidebarProfile: typeof import('./src/components/shared/SidebarProfile.vue')['default']
  }
}
